create table if not exists public.daily_goal_status (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  goal_name text not null,
  is_completed boolean not null default false,
  goal_date date not null,
  created_at timestamptz not null default now(),
  constraint daily_goal_status_goal_name_check check (
    goal_name in (
      U&'Sleep at least 7\20138 hours',
      U&'Drink 2\20133 liters of water',
      'Walk at least 5000 steps',
      'Limit sugary foods',
      U&'Practice mindfulness (5\201310 min)'
    )
  ),
  constraint daily_goal_status_unique unique (user_id, goal_name, goal_date)
);

create table if not exists public.weekly_goal_status (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  day_name text not null,
  goal_name text not null,
  is_completed boolean not null default false,
  week_start_date date not null,
  created_at timestamptz not null default now(),
  constraint weekly_goal_status_day_name_check check (
    day_name in (
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday'
    )
  ),
  constraint weekly_goal_status_goal_name_check check (
    goal_name in (
      U&'Sleep at least 7\20138 hours',
      U&'Drink 2\20133 liters of water',
      'Walk at least 5000 steps',
      'Limit sugary foods',
      U&'Practice mindfulness (5\201310 min)'
    )
  ),
  constraint weekly_goal_status_unique unique (user_id, day_name, goal_name, week_start_date)
);

create index if not exists idx_daily_goal_status_user_date
on public.daily_goal_status (user_id, goal_date);

create index if not exists idx_weekly_goal_status_user_week
on public.weekly_goal_status (user_id, week_start_date);
