create table if not exists public.weekly_stress (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  stress_score integer not null check (stress_score between 0 and 100),
  recorded_date date not null,
  day_name text not null,
  week_start_date date not null,
  created_at timestamptz not null default now(),
  constraint weekly_stress_day_name_check check (
    day_name in (
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday'
    )
  ),
  constraint weekly_stress_user_recorded_date_unique unique (user_id, recorded_date)
);

create index if not exists idx_weekly_stress_user_week_start
on public.weekly_stress (user_id, week_start_date);

create index if not exists idx_weekly_stress_user_recorded_date
on public.weekly_stress (user_id, recorded_date);
